### ISSUE TITLE
Prebuilt binaries

### ISSUE THREAD

**Issue by readysloth** [p-e-w/shin#10]
It would be really cool if release page would also contain prebuilt binaries, so users would not need install Go compiler and etc

**Comment by p-e-w** [comment]
That doesn't make much sense IMO. Shin isn't a standalone program, it requires installation, so the binaries would need to be accompanied by various other files, and users would still need other programs (such as Make) to install Shin.

The proper solution is distro-specific binary packages, which contain both the executable and the component XML. But that's for distributions to do.
