### ISSUE TITLE
Works on Chrome & Pycharm, but not Gnome tooling

### ISSUE THREAD

**Issue by apockill** [p-e-w/shin#9]
Love the tool, I installed it and would like to fix an issue I have. I'm currently unable to activate it in tools like `gedit`, but it works in chrome and pycharm. I've installed `typing-booster` and can confirm that that is working on the aforementioned platforms.

Any tips or tricks for debugging this would be appreciated!

**Comment by p-e-w** [comment]
I just merged a PR from @Zachu that solves a similar problem (#5) they were having. Could you test whether this fixes it for you as well?

If not, the discussions in #5 and #6 contain steps that might help you figure out what's going on.

**Comment by apockill** [comment]
I tried that- this problem appears to be solved now!
